/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.legislative.master;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;


@StyleSheet
@Template(FormPage.class)
public class OrdinanceEntityEditPage extends javax.swing.JPanel {

    /**
     * Creates new form PersonnelPage
     */
    public OrdinanceEntityEditPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        xSuggest1 = new com.rameses.rcp.control.XSuggest();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("SP Members");
        xFormPanel2.setBorder(xTitledBorder1);
        xFormPanel2.setName("entity.rsno"); // NOI18N

        entityLookup1.setCaption("SP Member Name");
        entityLookup1.setCaptionWidth(150);
        entityLookup1.setName("entity.spmembername"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup1.setRequired(true);
        xFormPanel2.add(entityLookup1);

        xSuggest1.setCaption("Regular Session No.");
        xSuggest1.setCaptionWidth(150);
        xSuggest1.setHandler("rsLookup");
        xSuggest1.setName("entity.resno"); // NOI18N
        xSuggest1.setPreferredSize(new java.awt.Dimension(150, 20));
        xSuggest1.setRequired(true);
        xFormPanel2.add(xSuggest1);

        xIntegerField3.setCaption("SP No.");
        xIntegerField3.setCaptionWidth(150);
        xIntegerField3.setName("entity.spno"); // NOI18N
        xIntegerField3.setRequired(true);
        xFormPanel2.add(xIntegerField3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    private com.rameses.rcp.control.XSuggest xSuggest1;
    // End of variables declaration//GEN-END:variables
}
